version: '3.7'

services:
  web:
    container_name: client_web
    image: client_web
    build: packages/client
    expose:
      - '80'
    depends_on:
      - api
  api:
    container_name: server_api
    image: server_api
    build: packages/server
    expose:
      - '8080'
    restart: unless-stopped
  proxy:
    image: nginx:alpine
    container_name: proxy_service
    volumes:
      - './proxy.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
